### ISSUE TITLE
Shell Script Invocation Error Group  

### ISSUE THREAD

**Issue by guoliang1206** [pathsense/pathsense-samples-iOS#1]
This is the error message 

```
/Users/Guodada/Library/Developer/Xcode/DerivedData/Test-fzeizrhmizoqabfahizcpwarwtny/Build/Intermediates/Test.build/Debug-iphoneos/Test.build/Script-C77E49CC1E9B8B7E006674CE.sh: line 2: bash/Users/Guodada/Library/Developer/Xcode/DerivedData/Test-fzeizrhmizoqabfahizcpwarwtny/Build/Products/Debug-iphoneos/Test.app/Frameworks/PSLocation.framework/strip-frameworks.sh: No such file or directory
```

this is the build phase config 
![2017-04-10 6 55 04](https://cloud.githubusercontent.com/assets/12846676/24858536/4ed94288-1e1f-11e7-96bc-0b1b407b9138.png)

Where is the problem?

**Comment by guoliang1206** [comment]
and the message : No such file or directory ，I guess it is a path error,how to deal this?

**Comment by guoliang1206** [comment]
@PaulSchmitt

**Comment by guoliang1206** [comment]
![2017-04-10 6 42 41](https://cloud.githubusercontent.com/assets/12846676/24858136/8d435484-1e1d-11e7-9639-05ed7f1d3a25.png)
this is my project hierarchical structure

**Comment by guoliang1206** [comment]
![2017-04-10 6 52 54](https://cloud.githubusercontent.com/assets/12846676/24858502/2eb5a55a-1e1f-11e7-9ca3-a60833743149.png)

**Comment by PaulSchmitt** [comment]
After the word bash insert a space before the command -- see below -- that should fix your issue.

bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/PSLocation.framework/strip-frameworks.sh"
