### ISSUE TITLE
what is the purpose of method startMonitoringAmbientLocationChanges  ？

### ISSUE THREAD

**Issue by guoliang1206** [pathsense/pathsense-samples-iOS#2]
I have read the document, it said that  "Start monitoring ambient location changes. The behavior of this service is not affected by the desiredAccuracy or distanceFilter properties. Locations will be delivered through the same delegate callback as the standard location service. You can expect to recieve sparce location data intermittenly."

And when I invoke the startMonitoringAmbientLocationChanges ,as it said, the delegate method "locationmanager:didUpdateLocations" doesn't  called anytime.

So when I want draw the path from coordinates, it doesn't  invoke the delegate method,and I can't get the coordinate, and I can't draw the line. The system method "startUpdatingLocation" is works better than this. 

If I want monitor the user's track and draw the polyline on the map, Which method can I use?

**Comment by guoliang1206** [comment]
And how to realize TruePath on iOS?

**Comment by guoliang1206** [comment]
if (activityType == PSActivityTypeWalking || activityType == PSActivityTypeRuning) {
        if (result != kPSLocationAccuracyPathSenseNavigation) {
            result = kPSLocationAccuracyPathSenseNavigation;
        }
    }

if I set it like this, is it on TruePath mode by walking and running?

**Comment by PaulSchmitt** [comment]
>If I want monitor the user's track and draw the polyline on the map, Which method can I use?

"Start monitoring ambient location changes" is not meant to give you enough locations to draw an exact path during a single session. It will give you locations intermittently similar to (but more often then) significant location change updates. 

To draw exact paths you should continue to use startUpdatingLocation. 

> And how to realize TruePath on iOS?

To use truePath you should set the location managers desiredAccuracy  to kPSLocationAccuracyPathSenseNavigation
[locMgr setDesiredAccuracy:kPSLocationAccuracyPathSenseNavigation];

>if I set it like this, is it on TruePath mode by walking and running?

yes this will turn TruePath on (but TruePath will try to snap to roads meant for inVehicle use, so for walking and running this may not be what you want/need).

**Comment by guoliang1206** [comment]
@PaulSchmitt  Thank you my friend,  these information are great helpful for me.
